### ISSUE TITLE
Slider with value is not controlled

### ISSUE THREAD

**Issue by maShcherbak** [n3r4zzurr0/react-range-slider-input#2]
Thank you for the great slider!

I have a question regarding usage of "value" prop. When I am trying to pass the value and control it with "onInput", I receive fully disabled slider. Can someone please help me to understand what I'm doing wrong?

Here the link to codesandbox with an example: https://codesandbox.io/s/blue-water-skrbr4?from-embed

**Comment by n3r4zzurr0** [comment]
Hey, thanks for pointing it out. It turned out to be a bug and is fixed now. Just update the package and you'll be good to go.
