### ISSUE TITLE
Incompatible with next js

### ISSUE THREAD

**Issue by Lord-AY** [n3r4zzurr0/react-range-slider-input#3]
Not compatible with next js as a global css is being imported

Error Message
`error - ./node_modules/react-range-slider-input/dist/components/index.css
Global CSS cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-npm
Location: node_modules/react-range-slider-input/dist/components/RangeSlider.js`

More info: [https://nextjs.org/docs/messages/css-npm](https://nextjs.org/docs/messages/css-npm)

**Comment by roshan-gh** [comment]
Also I have this problem too

**Comment by m-negahi** [comment]
any solution?

**Comment by Lord-AY** [comment]
sadly no

**Comment by n3r4zzurr0** [comment]
I have published a new version of the package where the internal reference to the CSS file has been removed. You will have to import the CSS file separately in your app, which will work fine with Next.js.

```js
import RangeSlider from 'react-range-slider-input';
import 'react-range-slider-input/dist/style.css';
```
