### ISSUE TITLE
Error thrown when resizing the window

### ISSUE THREAD

**Issue by ckeeney** [n3r4zzurr0/react-range-slider-input#4]
When I resize the window I get an error

```
TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

```

This error does not seem to affect the functionality in my use case, but the error is thrown for each resize event fired. 

I assume this is coming from the code below, but I don't understand how `window` could be undefined when I'm manually resizing my browser window.

https://github.com/n3r4zzurr0/react-range-slider-input/blob/aebeef05d853caeed5e81fd6d7ba315665b6c030/src/lib/components/RangeSlider.js#L357-L369

[chrome_0leDrxZjEX.webm](https://user-images.githubusercontent.com/8799010/202928265-3425abba-8a4d-4f91-b67c-982a810cdc82.webm)

I'm using `next.js` and this error happens in development and production.

**Comment by n3r4zzurr0** [comment]
The problem was that the global event listeners weren't being removed on unmounting. I have pushed an update that fixes this issue.
