### ISSUE TITLE
className="single-thumb" doesn't hide first thumb

### ISSUE THREAD

**Issue by JonathanMSifleet** [n3r4zzurr0/react-range-slider-input#5]
```
import Slider from 'react-range-slider-input';
import 'react-range-slider-input/dist/style.css';
...
const [sliderVal, setSliderVal] = useState(5000);
...
<Slider
  className="single-thumb"
  max={10000}
  min={0}
  onInput={(value: number) => setSliderVal(value[1])}
  rangeSlideDisabled={true}
  step={100}
  thumbsDisabled={[true, false]}
  value={[0, sliderVal]}
/>
```
With the code above the first thumb is still displayed.
[Image](https://i.imgur.com/yLC4Gd2.png)
Using v3.0.7.

**Comment by vincenzo-antolini-os** [comment]
3.0.6 and 3.0.7 doesn't hide the first thumb.
Try to add this custom css

```
.single-thumb .range-slider__thumb[data-lower] {
    width: 0;
}

.single-thumb .range-slider__range {
    border-radius: 6px;
}
```

**Comment by n3r4zzurr0** [comment]
The class `single-thumb` isn't shipped with this package. It's just one of the use cases. You will have to write a custom class as @vincenzo-antolini-os has stated above.

[CodeSanbox Demo](https://codesandbox.io/s/react-range-slider-input-demo-ymw2kp?file=/src/App.js)
